### ISSUE TITLE
imu ve zed kamera yüklemeleri

### ISSUE THREAD

**Issue by aysegulucar2016** [openzeka/openzeka-marc-doc#3]
Imu ve zed kamera yüklemeleri unutulmuş sanırım.  Ekleyebilir misinz?

**Comment by developer600** [comment]
Open zeka ile ciddi ilginen proje geliştirecek kadar kendisine güvenen gençler aranıyor...! 14.03.2018, 19:33, "aysegulucar2016" <notifications@github.com>:imu ve zed kamera yüklemeleri unutulmuş sanırım.
